FROM python:3.8.10-slim-buster

RUN apt-get update && apt-get install -y build-essential
# pip psycopg2 needs libpq-dev
RUN apt-get install -y libpq-dev

WORKDIR /airflow

RUN pip install --upgrade pip

COPY requirements.txt /airflow/
COPY . /airflow/

RUN pip install -r requirements.txt
RUN pip install -e .
